" Basics
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set hidden
set nobackup
set nowritebackup
set noswapfile
set path+=**
set wildmode=longest,list,full
set wildmenu
set encoding=utf-8
set showmatch
set background=dark
" set paste
set ruler
" set relativenumber

"Statusline
set laststatus=2

" Searching
set ignorecase
set incsearch
set hlsearch

" Splits behavior
set splitbelow
set splitright

" Word wrap
set wrap
set linebreak

" Term escape enters normal mode
tnoremap <Esc> <C-\><C-n>

" Netrw
let g:netrw_banner=0
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()

" Automatically install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

" Plugins
call plug#begin('~/.vim/plugged')

" Auto adjust indentation
Plug 'tpope/vim-sleuth'

" Language pack
Plug 'sheerun/vim-polyglot'

" Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Commenting
Plug 'tpope/vim-commentary'

" File explorer
Plug 'preservim/nerdtree'
let g:NERDTreeWinPos="right"
let NERDTreeMinimalUI=1
nnoremap <C-t> :NERDTreeToggle<CR>:NERDTreeRefreshRoot<CR>:wincmd p<CR>
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

" File navigation
Plug 'ctrlpvim/ctrlp.vim'

" Supertab
Plug 'ervandew/supertab'
let g:SuperTabDefaultCompletionType="context"

" Lining
Plug 'dense-analysis/ale'
let g:airline#extensions#ale#enabled=1
let g:ale_sign_column_always=1
let g:ale_fix_on_save=1

" Terraform
Plug 'hashivim/vim-terraform'
let g:terraform_align=1
let g:terraform_fmt_on_save=1

" Markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_new_list_item_indent=0
let g:vim_markdown_auto_insert_bullets=1

" Svelte
Plug 'evanleck/vim-svelte', {'branch': 'main'}
let g:svelte_indent_script=0
let g:svelte_indent_style=0

call plug#end()

" Install missing plugins on startup
autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif
